# Generated by Django 5.0.2 on 2024-02-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco_titulo', models.CharField(max_length=200)),
                ('bloco_texto', models.CharField(max_length=500)),
                ('data_pub', models.DateTimeField(verbose_name='data de criação')),
            ],
        ),
    ]
